@echo off
cls
bt doscolor 9 9
bt sirene 20 200 20 20 1 /s+ /f+
bt janela 2 3 22 5 25 normal
bt cursor 4 4 desligar
bt typeit 31 25 200 20 20 BatchÿToolsÿDemoÿ Û
bt pausa 4000
bt cursor 4 4 desligar
bt typeit 31 25 200 20 20 ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ Û
bt sirene 20 200 20 20 1 /s+ /f+
bt doscolor 9 9
bt scroll 2 3 31 200 Aÿdataÿactualÿ: esq
bt fade 2 4 25 200 ษออออออออออออออออออออออออออป fora
bt fade 2 5 25 200 บÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿบ fora
bt fade 2 6 25 200 ศออออออออออออออออออออออออออผ fora
bt cursor 4 5 desligar
bt data 31 por si
bt scroll 2 8 31 200 Asÿhorasÿso: esq
bt fade 2 9 25 200 ษอออออออออออออป fora
bt fade 2 10 25 200 บÿÿÿÿÿÿÿÿÿÿÿÿÿบ fora
bt fade 2 11 25 200 ศอออออออออออออผ fora
bt cursor 4 10 desligar
bt relogio 31 cent
bt cursor 4 5 desligar
bt typeit 31 25 200 20 20 ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ Û
bt cursor 4 10 desligar
bt typeit 31 25 200 20 20 ÿÿÿÿÿÿÿÿÿÿÿ Û
bt doscolor 7 0
cls
bt janela 2 2 30 5 9 normal
bt cursor 4 3 desligar
bt typeit 7 9 200 20 20 BatchÿToolsÿv1.1ÿ(c)ÿ1994 Û
bt cursor 4 4 desligar
bt typeit 7 9 200 20 20 LuisÿManuelÿSantosÿGuerra Û
bt cursor 1 5 ligar
