@echo off
cls
bt scroll 34 2 7 50 Demonstra‡„oÿdoÿBatchÿToolsÿv1.1 dir
bt scroll 31 3 7 50 porÿLuisÿManuelÿSantosÿGuerra dir
bt pausa 3000
cls
bt fade 2 1 9 100 DocumentoÿBatchÿToolsÿv1.1 fora
bt fade 2 2 7 50 ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ fora
bt fade 2 24 7 50 ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ fora
bt browse 2 3 79 23 9 9 bt.txt
cls
bt cursor 1 2 desligar
bt typeit 7 7 1 1 100 Batch  Tools
bt cursor 1 2 desligar
bt typeit 7 7 1 1 100 BatchÿTools ÿv1.1ÿ
bt cursor 1 3 ligar
