@Echo Off
Cls
Bt3 TypeIt3 1 2 9 10 Demonstra‡„oÿdaÿfun‡„o
Bt3 TypeIt3 1 3 9 10 AppendÿemÿBatchÿToolsÿ3ÿv1.0
Bt3 TypeIt3 1 5 15 10 AppendÿEsq_Dtro
Bt3 Append 65 6 7 25 Isto_‚_um_teste esq_dtro
Bt3 TypeIt3 1 5 15 10 AppendÿEsq_Fora
Bt3 Append 65 6 7 50 Isto_‚_um_teste esq_fora
Bt3 TypeIt3 1 5 15 10 AppendÿDir_Dtro
Bt3 Append 1 6 7 25 Isto_‚_um_teste dir_dtro
Bt3 TypeIt3 1 5 15 10 AppendÿDir_Fora
Bt3 Append 1 6 7 50 Isto_‚_um_teste dir_fora
Cls
