@Echo Off
Cls
Bt3 Append 1 2 9 5 Demonstra‡„oÿdaÿfun‡„o dir_dtro
Bt3 Append 1 3 9 5 Browse2ÿemÿBatchÿToolsÿ3ÿv1.0 dir_dtro
Bt3 TypeIt3 1 4 7 0 ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
Bt3 TypeIt3 1 24 7 0 ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
Bt3 Append 60 25 9 10 TecleÿESCÿparaÿsair esq_dtro
Bt3 Browse2 1 5 79 23 7 9 500 bt3.pas
Cls
