     /********************************************************************
      *                                                                  *
      *   Fonte: WinInfID.h  	                                         *
      *                                                                  *
      ********************************************************************/

#ifndef __WININFOID__H
#define __WININFOID__H

#define   IDM_GRAVARINFORMACAOCOMO            101
#define   IDM_SAIR                            102
#define   IDM_SOBRE                           103


#endif
