#ifndef __WGMENUDF_H
#define __WGMENUDF_H

//Definições dos códigos dos comandos do menu
#define IDM_INICIAR     1
#define IDM_SAIR        2
#define IDM_1JOGADOR    3
#define IDM_2JOGADORES  4
#define IDM_BOLAS       5
#define IDM_CRUZES      6
#define IDM_INDEX       7
#define IDM_SOBRE       8
#define IDM_NIVEL1		9
#define IDM_NIVEL2		10
#define IDM_NIVEL3		11

// Definições dos códigos das strings de texto de informação
#define ITID_WINBALL    1
#define ITID_WINCROSS   2
#define ITID_EMPATE     3

// Código para a string de aviso de programa já presente
#define SSID_NOMORE     16

// Identificação do botão OK para a Dialog Box de Sobre
#define IDB_OK          1

#endif //wgmenudf.h
