@Echo Off
cls
Rem Descri‡„o: Uso de Crush Fora
Bt2 Crush 1 2 9 100 Demonstra‡„oÿdaÿfun‡„o fora
Bt2 Crush 1 3 9 100 MoveCorÿdeÿBatchToolsÿ2ÿv1.0 fora
Rem Descri‡„o: Uso de MoveCor Esq, Dir e Ambos
Bt2 MoveCor 1 5 9 31 100 MoveCorÿESQ 10 esq
Bt2 MoveCor 1 5 9 31 100 MoveCorÿDIR 10 dir
Bt2 MoveCor 1 5 9 31 100 MoveCorÿAMBOS 5 ambos
Bt2 MoveCor 1 5 31 15 100 ÿFimÿdoÿTesteÿ 5 ambos
Rem Descri‡„o: Mudan‡a de cor com PaintTxt
Bt2 PaintTxt 1 1 9 1
Rem Descri‡„o: VScroll deixa rasto com a cor acima atribuida
Bt2 VScroll 1 6 9 50 ÿMoveCorÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ baixo
Echo.
