'Definições globais.

Type registo1              '
     seq As String * 3     '  Define os
     moedas As Integer     '
End Type                   'ficheiros de
Type registo2              '
     numvezes As Integer   '  registos
     moedas As Integer     '
End Type
Global pont(7) As registo1   '
Global sim(10) As registo2   '
Global num As Integer        ' Dimensiona as
Global numsim As Integer     '
Global rol1 As Integer       ' variáveis globais
Global rol2 As Integer       '
Global rol3 As Integer       '
Global comp As String        '
Global saldomoedas As Integer'


